; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;,
;        "-DARDUINO_USB_MODE=1",
;        "-DARDUINO_USB_CDC_ON_BOOT=1"
;
;

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
monitor_speed = 115200
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
    -DARDUINO_USB_MODE=0 
    -DUSE_TINYUSB
    -DCFG_TUD_ENABLED
    -DCFG_TUD_MIDI
    '-DCFG_TUSB_CONFIG_FILE="/Users/felix/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include/arduino_tinyusb/include/tusb_config.h"'
;    -DCFG_TUSB_DEBUG=2
;    -DCFG_TUSB_DEBUG_PRINTF=TinyUSB_Ser1Debug
lib_deps = 
    adafruit/Adafruit TinyUSB Library@^1.13.3

;lib_deps =  	adafruit/Adafruit TinyUSB Library
;	        fortyseveneffects/MIDI Library

